version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - api
  api:
    build: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - 5000:5000
    container_name: api
    depends_on:
    - db
  db:
      image: mongo
      restart: always
      container_name: mongo
      volumes:
          - ./data-node:/data/db
      ports:
          - 27017:27017
      command: mongod --noauth 
